- store/store.go
@timoman @skuehn @ericchang: Here's the bug that @timoman's "friend" ran into a while back. It was with some other tool but with the same underlying issue. 
In this case, if someone was using something like `~/botstorage/`, the resulting files would get created as `./~/botstorage` instead of resolving the `~` as the `home` directory. 
This fixes it so that no more evil `~` get inadvertently created.
> Fix Storage Path Not Resolving ~ as Home Directory.

- README.md
- config/config.go
- plugins/emojibanner.go
- plugins/fingerquoter.go
- plugins/imager.go
- plugins/karma.go
- slackscot.go
- version.go
@s-machina: I thought maybe you'd enjoy reviewing this. I started out wanting to update `slackscot` to a `go` `slack API` integration that was still actively maintained and it looks like https://www.github.com/nlopes/slack is exactly that. But I also wanted to make things a little cleaner and remove some of the extra cruft that I had added in a haste when I was trying to get `youppi` out during the course of only a few days. It's now cleaner even though I'd like to revisit some patterns later on (I've been debating wether or not to use plain functions vs functions with structs as receivers in a few places). 
I think this is mostly the start of something nice. In my short-term todo, I have:
- I'd like to handle triggering messages that get updated as well as updated messages that should …
> Migrate Slackscot From james-bowman/slack To nlopes/slack API

- help.go
- plugins/ohmonday.go
- plugins/ohmonday_test.go
- schedule/schedule.go
- schedule/schedule_test.go
- slackscot.go
Improving code quality metrics 
Description of the changes
Remove redundant `Schedule` in `schedule.ScheduleDefinition`
None
> Remove Redundant Schedule in schedule.ScheduleDefinition

- plugins/fingerquoter.go
- plugins/fingerquoter_test.go
The finger quoter would ignore sub-second precision and therefore could have caused many messages in the same second to trigger quoting which would be awkward. Making this unique by including the decimals in the random generator seed.
> Fix FingerQuoter Seed In Handling of MessageID for Random Generator

- .travis.yml
- go.mod
- go.sum
* Upgrade to official tag of `nlopes/slack` (`0.5.0`).
* Remove scripting gymnastics to install `test-reporter` in `.travis.yml`.
> Upgrade to nlopes slack 0.5.0

- .travis.yml
`test-reporter` seems to be reporting coverage for itself instead of this repo. This enables `debug` to investigate.
*Update*: Implemented ugly hack in [fork](https://github.com/alexandre-normand/test-reporter) to fallback on resolving files by removing the non-physical `module` version prefix from it when failing with the "normal path. This is not how proper `module` support should be added to `test-reporter` but I needed to unblock broken (and wrong) test coverage reporting now. Note that issue https://github.com/codeclimate/test-reporter/issues/378 should allow this hack to go away.  
> Add Debugging to Investigate test-reporter Misreporting Coverage

- plugins/emojibanner.go
- plugins/emojibanner_test.go
Add a quick test for `emojiBannerMaker` plugin with wrong usage and simplified the `Answer`'s `returns`.
> Add Wrong Usage Test for Emoji Banner Maker Plugin

- plugins/fingerquoter.go
- plugins/fingerquoter_test.go
Add more tests for `fingerQuoter` plugin and fix `whitelist` defaulting to all channels. 
> Add More Tests for FingerQuoter Plugin

- help.go
- plugins/emojibanner.go
- plugins/emojibanner_test.go
- plugins/fingerquoter.go
- plugins/fingerquoter_test.go
- plugins/karma.go
- plugins/karma_test.go
- plugins/versioner.go
- plugins/versioner_test.go
- slackscot.go
- slackscot_test.go
Instead of passing the normalized text on `Match` only along with the
slack message and inconsistently passing only the slack `Msg` on `Answer`,
there is now a struct that embeds the `slack.Msg` and adds a normalized
version of the text and that's used in both `Match` and `Answer`.
> Clean Up Match and Answer API

- README.md
- help.go
- plugins/emojibanner.go
- plugins/emojibanner_test.go
- plugins/fingerquoter.go
- plugins/fingerquoter_test.go
- plugins/karma.go
- plugins/karma_test.go
- plugins/versioner.go
- plugins/versioner_test.go
- slackscot.go
- slackscot_test.go
Made `Answerer` return an `Answer` struct that can be more amenable to adding capabilities in the future (like message options to allow a plugin action to decide to do threaded replying, for example). It should be easy to add but I want to sleep on it to not just stick an array of `slack.MsgOption` in there which would make it hard on plugin authors to test (because of how MsgOptions are functions acting on a `slack` private struct). 
> Allow Answering Capabilities to be Extended in the Future

- README.md
- answer.go
- answer_test.go
- help.go
- slackscot.go
- slackscot_test.go
- version.go
This adds the ability for plugins to dictate if the `Answer` should be sent as a threaded reply with broadcast or not. 
> Add Ability for Actions to Reply in Threads With/Without Broadcast

- README.md
- plugins/fingerquoter.go
- plugins/fingerquoter_test.go
- plugins/ohmonday.go
- plugins/ohmonday_test.go
- version.go
Add support for a list of channel ids to send a greeting to to the `Oh Monday` plugin.
> Add Multi-Channel Support to Oh Monday

- plugins/emojibanner.go
- plugins/emojibanner_test.go
- plugins/fingerquoter.go
- version.go
Limit emoji banner to words of 5 characters or less.
> Limit Emoji Banners to 5 Characters

- plugins/karma.go
- plugins/karma_test.go
- version.go
Tweak `karma` to allow hyphens, apostrophes and user ids (rendered using the user's real name).
> Add Support for User Ids, Hyphens and Apostrophes in Karma

- slackscot.go
- version.go
There was a bug where new messages triggered on a message update would not show up if the configuration or the plugin made it such that this would be a threaded reply. The problem was that the thread timestamp was wrong and therefore no message existed to issue a threaded reply to. 
> Fix Message Update Trigerring New Threaded Reply Message

- plugins/ohmonday.go
- version.go
Use downsized `gif` links for the ultra-large gifs (`>10 MB`).
> Use Downsized Oh Monday Gifs for Ultra Large Ones

- plugins/fingerquoter.go
- plugins/fingerquoter_test.go
- version.go
Added `ignoredChannelIDs` configuration to finger quoting to allow a _opt-out_ style instead of `opt-in`. 
> Add ignoredChannelIDs to Finger Quoter Plugin Configuration

- plugins/ohmonday_internal_test.go
Add a test to enforce `Oh Monday` gifs to be smaller than 10MB. This means that contributions to the curated list will get validated for size during the PR build 🎉 .
> Add Test to Break Build and Enforce 10MB Limit on Oh Monday Gifs

- slackscot.go
- version.go
Drop command processing when messages start with '@selfName' or 'selfName'. I never liked those and it makes the parsing simpler (a `HasPrefix` instead of a regex). 
> Only Process Commands on Direct Message and Message with @selfUserId

- slackscot.go
- slackscot_test.go
- version.go
Since the `Timestamp` is part of a message identification, `slackscot`
now uses the `timestamp` of the original message when processing message
updates. This is useful because plugins can use this to know when looking
at a message that it's the same as one previously seen.
One example of this is the `fingerquoter` that uses the timestamp as a seed to
random generation to decide on a match/trigger. Previously, a message update
would result in a different seed which would cause the previous reaction to be
deleted. Now `fingerquoter` can remain coherent as it sees the same timestamp/seed
which results in the same match/non-match. The reaction can change depending on the
message content changing but that seems consistent and reasonable too.
*   [x] I've …
> Have Message Updates Use the Original Message's Timestamp

- answer.go
- plugins/emojibanner.go
- plugins/fingerquoter.go
- plugins/fingerquoter_test.go
- plugins/triggerer.go
- store/leveldb_test.go
- test/assertaction/assertaction.go
- test/assertanswer/assertanswer.go
- test/assertplugin/assertplugin.go
- test/assertplugin/assertplugin_test.go
- test/emojireactioncaptor.go
- version.go
Finger quoting used to match on words only but irregardless of the context (that is something like `/hello/` could be a match. While preserving the same word length requirement, this is now implemented via a `regexp` that won't take words that aren't preceded by the start of a line or a space. 
> Tweak Finger Quoter's Finding of Word Candidates to Exclude Words in Non-Sentence Messages

- slackscot.go
- slackscot_test.go
- version.go
Fixes a bug manifesting itself when triggering commands in direct messages. A long output like `help` would cause a `message_replied` message to come in afterwards and this would cause the default command to run (since that was a direct message). Messages with the  `message_replied` subtype are now ignored.
> Ignore Messages with SubType message_replied

- plugins/triggerer.go
- version.go
`list triggers` and `list emoji triggers` were set to `hidden` but they shouldn't have. This fixes it. 
> Unhide List Trigger Commands From Triggerer

- plugins/triggerer.go
- plugins/triggerer_test.go
- version.go
The round bullet I had picked was just wrong. It looks like a speck of dust in `slack`.
> Improve Trigger List Formatting with a Bigger Round Bullet Symbol

- plugins/triggerer.go
- plugins/triggerer_test.go
- version.go
This makes registerer triggers be case-insensitive.
> Make Triggerer React Insensitively on Registerer Triggers

- plugins/karma.go
- plugins/karma_test.go
- version.go
This is for @doug-descombaz. Some tweaks to the `karma` regex to avoid registering `karma` on `sql` or `diff` outputs. The tradeoff (surprise?!) is that hyphenated words won't be captured like they used to. So `under-the-bridge++` would now be captured as `the-bridge++`. 
Wait? Did you see? How come I'm still capturing one hyphen? 
I thought it'd be sad to lose the ability to do composed first names like `s-m++` so I made it a special case. 
🙇 You're welcome.
> Prevent Karma to Register on SQL and diff Outputs

- README.md
- store/datastoredb/datastoredb.go
- test/assertplugin/assertplugin.go
- version.go
@s-machina: Here's a `datastore` implementation of the `StringStorer` interface. I tried to include a good usage example and documentation in the package but I can summarize a few things here:
*   The `name` passed to `datastoredb.New` maps to the datastore entity `kind`. Basically, this is how we `namespace` things and isolate plugins from each other. That way, they each get their own view even though you see everything for a project when you look at the Datastore web UI.  
*   The `gcloudProjectID` and the `gcloud credentials` (usually a credentials `json` file downloaded from https://console.cloud.google.com/apis/credentials/serviceaccountkey) are the only other things needed. 
I tried this with me personal account and `youppi` and it worked fine. Unfortunately, testing this would be …
> Add Google Cloud Implementation of StringStorer

- store/datastoredb/doc.go
This comment with the wrong import string made `godoc` not render the package doc at the expected URL. Removing it and letting it find the import on its own seems like a better idea. 
> Remove Bad Import String in store/datastoredb/doc.go

- README.md
- store/datastoredb/doc.go
- store/inmemorydb/doc.go
- store/inmemorydb/inmemorydb.go
- store/inmemorydb/inmemorydb_test.go
- version.go
Since the `datastore` might have cost for all the operations and we might be doing a lot of them (some plugins check the db on every message), I thought it would be a good idea to add a `inmemorydb` wrapping any `StringStorer` implementation. This keeps all data in memory so it's more for smaller datasets. Data is loaded from persistent store on creation and then puts/deletes are persisted. The reads are from the in-memory copy. 
Plugins usually have small datasets that will work well with this. If a plugin needed to store huge amounts of data, it would probably make sense to use another storage API anyway. 🤷‍♂️
> Add inmemorydb Wrapping StringStorer to Keep Data in Memory

- plugins/karma.go
- plugins/karma_test.go
- version.go
Reported this morning by a kind gentleman. I'm not proud of it but the way to check for a `karma top` / `karma worst` match was just stupid. This makes it better and adds tests to prove it.
> Fix Karma Top/Worst Crashing When No Count Provided

- plugins/triggerer.go
- plugins/triggerer_test.go
- version.go
- Fix bug with emoji triggers being saved even when the reaction didn't include
emojis (now slackscot should answer with details explaining no emojis were found)
- Add support for multi-line reactions to standard triggers
> Improve Usability of Triggerer

- answer.go
- answer_test.go
- config/config.go
- config/config_test.go
- slackscot.go
- slackscot_test.go
- version.go
This changes the behavior when a triggering message is on a `thread`. Before, the reactions would just show up in the channel and it could look odd for the general channel watchers that weren't also following or participating in the thread. So this changes that and has `answers` go to the `thread` if the message is already on one. It works when I try it live, too.
But the thing is, that's the part of the code I like less and I'm less happy with so I'm leaving this PR here and I'll try to think of a way to clean this up a bit. It's not terrible now but as I gain more experience with this, I feel like it's a good time to stop and see if I can improve this enough that I'd feel good about showing it to strangers (or friends and family). 
*   [x] I've executed …
> Send Answers to Existing Thread if Triggering Message was sent on Thread

- slackscot.go
- slackscot_test.go
- version.go
Prevent direct messaging with a `slackscot` to include threaded replies. It's difficult to imagine a use-case for threads in a direct conversation with `slackscot` and, in the meantime, it just feels inappropriate so I think this will be a nice improvement. 
> 🚫🧵 Disable Threaded Replies when Communication in Direct Messaging

- fileuploader.go
- fileuploader_test.go
- slackscot.go
- store/datastoredb/datastoredb.go
- store/datastoredb/doc.go
- store/inmemorydb/inmemorydb.go
- test/assertaction/assertaction.go
- test/assertplugin/assertplugin.go
- test/assertplugin/assertplugin_test.go
- test/capture/doc.go
- test/capture/emojireactioncaptor.go
- test/capture/fileuploadcaptor.go
- version.go
@doug-descombaz You don't have to review this but you might like to since that's the addition of the `FileUploader` plugin service we talked about. This is mostly adding a passthrough access to this [UploadFile](https://godoc.org/github.com/nlopes/slack#Client.UploadFile) api but I think that's the way to do it. 
To make it easier on plugin writers to validate that their commands/actions are doing the expected uploads, I added support in the `assertplugin` for capturing `FileUploadParameters` that triggered during the evaluation of a message. You might be interested in that and looking at its usage which is the test for that test function (`TestFileUploadCapture`).
*   [x] I've run `go …
> Add file uploader plugin service

- help.go
- slackscot_test.go
- version.go
The `help` plugin always sets threading _and_ broadcast. The more I see this in the real world™, the more I think that the use of thread broadcast should be reduced to exceptional cases. And `help` doesn't qualify for this so this fixes that.
> Remove Explicit WithBroadcast Answer Option to Help Plugin

- plugins/triggerer.go
- plugins/triggerer_test.go
- version.go
There were extra backticks surrounding multi-line reactions listed by triggerer's `list triggers` command. This fixes it.
> Fix Triggerer Rendering of Std Trigger List With Multi-Line Reactions

- slackscot.go
- slackscot_test.go
- version.go
The `default` command is a bit special and I missed it when I added the honoring of existing threads when posting reactions. 
> Fix Default Command Not Honoring Threads

- store/datastoredb/datastoredb.go
- store/datastoredb/doc.go
- version.go
When a deployment uses credentials rotation/leases, the `datastoredb` would eventually stop working and would error out on any operation with something like:
```
rpc error: code = Unauthenticated desc = transport: oauth2: cannot fetch token: 400 Bad Request Response: { "error": "invalid_grant", "error_description": "Not a valid email or user ID."}
```
This change addresses that by lazy reconnecting/recreating the `datastore` client when an error is encountered that _isn't_ one of:
*   datastore.ErrNoSuchEntity
*   datastore.ErrInvalidEntityType
*   datastore.ErrInvalidKey
Since now `datastoredb` has some meaningful logic instead of being a thin wrapper, I added an item to my backlog to add a test for it which will likely require some decoupling by adding small interfaces. 
*   [x] I've …
> Support gcloud Credentials Being Rotated and Lazy Recreate the DS Client

- store/datastoredb/datastore.go
- store/datastoredb/datastoredb_internal_test.go
- version.go
In adding an interface for `datastorer` in the last commit, I introduced a stack overflow because calls to the datastore would use itself instead of calling the embedded client. This was stupid and this fixes it.
> Fix Stackoverflow on All Invocations of datastore Client Methods

- plugins/triggerer.go
- plugins/triggerer_test.go
- version.go
Triggers registered would still match and react when a message would include the trigger as a substring (i.e. a trigger on `late` would provoke a reaction on a message including `later`). This now fixes it by matching a trigger only if it's surrounded by word boundaries. 
> Fix Triggerer Reacting on Registered Trigger Being Substrings on Words

- plugins/emojibanner.go
- plugins/emojibanner_test.go
- plugins/fingerquoter_test.go
- plugins/triggerer_test.go
- test/assertplugin/assertplugin.go
- test/assertplugin/assertplugin_test.go
- version.go
Coming back and revisiting the `emojibanner_test` after having gained some wisdom from writing more tests (and after having created `assertplugin`). 
This also moves the `t.testing` parameter in `assertplugin` to the `New` instead of having it passed on each `AnswersAndReacts` assertion. 
> Port Over Emoji Banner Maker Test to Use assertplugin

- plugins/karma_test.go
- plugins/ohmonday_test.go
Remove some redundant code in `karma_test` by migrating it to use `assertplugin`. 
> Migrate karma_test to Use assertplugin

- chatdriver.go
- plugins/ohmonday.go
- plugins/ohmonday_test.go
- test/assertplugin/assertplugin.go
- test/assertplugin/assertplugin_test.go
- test/capture/sendercaptor.go
- version.go
Add support to `assertplugin` to drive a plugin's `ScheduledActions` and assert the expected messages are being sent. As usual, injected services are set on the plugin prior to driving the actions in case the plugin needs those (although the `RunsOnSchedule` validator currently doesn't have a hook to check for emoji reactions or files uploaded). 
> Add Support in assertplugin for Scheduled Actions Testing

- fileuploader.go
- store/datastoredb/datastoredb_internal_test.go
- test/assertplugin/assertplugin.go
- test/assertplugin/assertplugin_test.go
- test/capture/emojireactioncaptor.go
- test/capture/fileuploadcaptor.go
- test/capture/sendercaptor.go
- version.go
Fix some recently introduced typos and bad copy-pasta in `godoc`. Since I'd consider wrong documentation a bug, I'm bumping the patch version number.
> Fix Some Godoc Typos and Bad Copy-Pasta 🍝

- plugins/storer_mock_test.go
- plugins/triggerer_test.go
I was about to add some error tests to `karma_test` when I realized I could reuse my mock storer but since it was hand-coded, I thought I'd convert it first to a standard testify mock so I'd have more control over it. 
> Convert triggerer_test to Use a Testify Mock Storer

- plugins/karma.go
- plugins/karma_test.go
- version.go
Also improve message when the karma count requested is higher than the number
of stored items to use the returned count rather than the requested count
> Add Error Cases to Karma Test

- plugins/ohmonday_test.go
- test/assertplugin/assertplugin.go
- test/assertplugin/assertplugin_test.go
- version.go
Add support for validating `file uploads` to `assertplugin.RunsOnSchedule`. 
> Add Support for File Uploads Validation to assertplugin.RunsOnSchedule

- chatdriver.go
- plugins/ohmonday.go
- slackscot.go
- slackscot_test.go
- test/assertplugin/assertplugin.go
- test/assertplugin/assertplugin_test.go
- test/capture/sendercaptor.go
- version.go
This cleans up the `ScheduledAction` api and makes a few things simpler. Now `ScheduledActions` receive no parameters which means that to do something useful, that action should be written so it has access to its plugin services. While that seems like taking away something, it's actually more formalizing that a scheduled action can do anything it wants by using the plugin services (like upload a file maybe 🤷‍♂️). 
In the process, I also cleaned up the `RealTimeMessageSender` and made it so that `slack.RTM` implements it without wrapping. There's also no more `GetAPI` which was not something that I should have added in the first place. 
*   [x] I've run `go test ./...` and confirmed the …
> Allow RTM Msg Senders to Use Message Options

- store/datastoredb/datastoredb.go
- store/datastoredb/datastoredb_internal_test.go
- store/store.go
Add new `SiloStringStorer` with support for siloed key/value storage. Also implement the new interface in `datastoredb`. 
> Add SiloStringStorer with datastoredb Implementation

- store/leveldb.go
- store/leveldb_test.go
- version.go
Implement `SiloStringStorer` with `leveldb`. While that implementation isn't the main production one anymore, it remains useful for testing beyond what a mock storer can do so this is useful. 
> Implement SiloStringStorer in leveldb Implementation

- plugins/karma.go
- plugins/karma_test.go
- plugins/storer_mock_test.go
- version.go
This changes how `karma` keeps track of things. Instead of being a single global map, it's now siloed by channel. This means that the previously recorded karma will get forgotten in the default silo/namespace. I think that given the non criticality of the feature, it's forgivable. 
Since it might still be fun to be able to see global entries, I'll probably add commands for `global karma top` and `global karma worst` soon. 
> Change Karma Plugin to Track Per Channel Instead of Globally

- store/datastoredb/datastoredb.go
- store/datastoredb/datastoredb_internal_test.go
- store/leveldb.go
- store/leveldb_test.go
- store/store.go
- version.go
Add `GlobalSiloStringStorer` to allow global scans returning all db contents regardless of silo name. 
Also made the key storage in `leveldb` more robust by using a delimiter (`\u00DA`) which isn't a valid utf8 character. 
Importantly, the new interface comes with implementations in `datastoredb` and `leveldb`. Coming next, the `karma` plugin will use `GlobalSiloStringStorer` to support new commands for global karma retrieval. 
> 🌍 Add GlobalSiloStringStorer Interface with leveldb and datastoredb Implementations 

- plugins/emojibanner.go
- plugins/emojibanner_test.go
- version.go
The message said words longer than `5` were disallowed but it was actually messages longer than 4. This fixes that erroneous message. 
> Fix Emoji Banner Allowed Word Lenght in Error Message

- plugins/karma.go
- plugins/karma_test.go
- plugins/storer_mock_test.go
- version.go
This adds two new commands to the `karma` plugin:
`karma global top <count>` and
`karma global worst <count>`
Hopefully it's intuitive as to what they do but it's basically the same as the top/worst commands except that the results include karma across all channels. 
> 🌓 Add Global Karma Commands to Karma Plugin

- store/inmemorydb/inmemorydb.go
- store/inmemorydb/inmemorydb_test.go
- version.go
Have the `inmemorydb` Implement the full `GlobalSiloStringStorer` for full support for the latest API. 
> Have inmemoerydb Implement GlobalSiloStringStorer

- plugins/karma.go
- plugins/karma_test.go
- version.go
Adds a `karma clear` command to clear a channel's recorded karma. 
> Add Karma Clear Command to Clear Channel Karma

- plugins/triggerer.go
- plugins/triggerer_test.go
- version.go
- Optional flag `anywhere` to trigger registration commands to register a global trigger (channel-trigger is now the default)
- Delete command deletes channel trigger first and deletes global trigger if no channel trigger found
> Add Per-Channel Triggering Functionality to Triggerer

- store/datastoredb/datastoredb.go
- store/datastoredb/datastoredb_internal_test.go
- version.go
I misunderstood the `datastore` api and I thought that not providing a `namespace` would imply querying _all_ namespaces. If I had thought about the default/zero value of the namespace in `Query`, I wouldn't have made that stupid mistake.
Anyway, the correct way to do this is to do a key-only scan of `__namespace__` to get the list of namespaces and then query each one. 
> 🐲 Fix Broken Global Scan Implementation in datastoredb

- plugins/karma.go
- plugins/karma_test.go
- version.go
By relaxing the regex and allowing an extra space between a user id and the increment/decrement `<@user> ++`, it allowed it for any word. I knew and I thought about this but it turns out it's more annoying than I anticipated. 
The regex is starting to look a bit crazy (not too crazy but it's not a delight to the eye) but it's still reasonable. The worse is having two different matching groups but it also helps keeping the expression for each one more readable so maybe it's even a net win. 
> 🚫◻️ Disallow Extra Space Between Thing and Symbol Except for User IDs

- plugins/karma.go
- plugins/karma_test.go
- version.go
This makes the count parameter optional when requesting a top/worst listing. Most people didn't want to have to think about a number of items to list so it makes sense to allow it and have default. 
> 😇 Make Count Optional in Top/Worst Karma Commands

- plugins/karma.go
- plugins/karma_test.go
- slackscot.go
- slackscot_test.go
- version.go
Add managed plugin command namespacing. Plugins don't have it set by default but if desired, they can have `NamespaceCommands` set to `true` for `slackscot` to check for commands to match the plugin name. This can also be disabled at runtime with`OptionNoPluginNamespacing` if, for example, an instance of slackscot is meant to run a single plugin and namespacing is superfluous. 
The `karma` opts-in toe `NamespaceCommands` and shows how plugins should expect a normalized text stripped of the namespace. `Slackscot` manages stripping it if namespacing is enabled at runtime. 
> 🏷 Add Managed Plugin Command Namespacing

- plugins/karma.go
- plugins/karma_test.go
- version.go
Change `karma` listing commands to include a `gif` in the header and replace the ascii banner by some more emoji padding.
Increment the version like this was a bug fix since its ugliness could be considered a bug. 
> 🍃 Make Karma Report Formatting a Little Nicer

- plugins/karma.go
- plugins/karma_test.go
- version.go
Introduced a tiny block kit formatting error in my last changes that caused karma listing reports to send invalid slack messages rejected at runtime. This fixes it. 
> 🐞 Fix Broken Block Kit Content in Karma Listing Causing No Answers

- help.go
- help_internal_test.go
- slackscot.go
- slackscot_test.go
- version.go
Forgot to include support in the `help` for plugin namespacing. That's now taken care of. 
> 🐌 Fix Help Missing Plugin Namespace in Usage String When In Use

- README.md
- help_internal_test.go
- slackscot.go
- slackscot_test.go
- version.go
Replace `slackscot.NewSlackscot` by `slackscot.New` (reads better and is more idiomatic). `NewSlackscot` remains for backward compatibility but will be gone when switching to `2.0.0`.
> 🕸 Deprecate slackscot.NewSlackscot In Favor of slackscot.New

- slackscot.go
Improve `godoc` of `Plugin`. Mainly so that the example usage for `NamespaceCommands` renders properly.
> 📝 Improve godoc of Plugin

- actions/actions.go
- actions/actions_test.go
- builder.go
- builder_test.go
- doc.go
- plugin/plugin.go
- plugin/plugin_test.go
- plugins/emojibanner.go
- plugins/emojibanner_test.go
- plugins/fingerquoter.go
- plugins/fingerquoter_test.go
- plugins/karma.go
- plugins/karma_test.go
- plugins/ohmonday.go
- plugins/ohmonday_test.go
- plugins/triggerer.go
- plugins/triggerer_test.go
- plugins/versionner.go
- plugins/versionner_test.go
- schedule/schedule.go
- schedule/schedule_test.go
- slackscot.go
- slackscot_test.go
- test/assertplugin/assertplugin.go
- version.go
Add fluent-apis for setting up:
- actions: `gitHub.com/alexandre-normand/slackscot/actions`
- plugins: `gitHub.com/alexandre-normand/slackscot/plugin`
- schedules: `gitHub.com/alexandre-normand/slackscot/schedule`
- bots: `gitHub.com/alexandre-normand/slackscot` (via `builder.go`)
> Fluent api for plugin creation

- .travis.yml
Remove forked `test-reporter` from travis configuration. This was needed at some point but it's not required anymore since the current version works fine with the stock `test-reporter`. 
> Remove Unnecessary Usage of test-reporter fork in Travis Config

- help.go
- help_internal_test.go
- version.go
The `help` would show section headers such as "I currently support the following commands" even when no visible command existed. The header would correctly not be visible if no commands existed but if all that did exist were `hidden` and there was nothing to show, the header would still be there with the awkwardly empty section.
> 👻 Fix Help Showing Section Headers With No Actions to Show Because of Hidden Flag

- test/assertanswer/assertanswer.go
- test/assertplugin/assertplugin.go
This adds `godoc` examples for `assertplugin` and `assertanswer` packages.
> 📗 Add godoc Examples in assertanswer and assertplugin

- plugins/karma.go
- plugins/karma_test.go
The ranking icon image links were no longer valid which caused slack to error out with the block kit that included them. This made me revisit the top/worst report format and I removed the icons and banner pictures for a more compact and safer version.
> 🐛 Fix Karma Top/Worst Report Broken Because Img Links No Longer Valid

- plugins/karma.go
- plugins/karma_test.go
- version.go
I wasn't so well-versed when I did the initial implementation of the karma reporting with `block kit` and I had wrongly used `context` blocks. This replaces context blocks by regular text content blocks.
> 💅 Replace Context by Regular Text Blocks in Karma Reports

- answer.go
- answer_test.go
- plugins/karma.go
- plugins/karma_test.go
- version.go
Add `AnswerEphemeral` answer option to have the `answer` be sent as an ephemeral message.
And a few `karma` features:
- Ability to increment/decrement by more than 1 (up to 5) by using
additional + or - signs
- Block self attribution of karma and send ephemeral message
to author to indicate behavior
- Hide karma reset command to prevent abuse
> 🧮 Add AnswerEphemeral Option and a Few Karma Plugin Features

- slackscot.go
- slackscot_test.go
- version.go
`AnswerEphemeral` wasn't propagated to the `PostMessage` as it should have been. Added a test in `slackscot_test.go` for that and also fixed the test not exercising the `make` test command like it was supposed to. 
> 👻 Fix Ephemeral Answer Option Not Fully Propagated to Sent Message

- answer.go
- fileuploader.go
- plugins/karma.go
- plugins/karma_test.go
- schedule/schedule.go
- slackscot.go
- slackscot_test.go
- test/assertplugin/assertplugin.go
- version.go
In an oversight that became a habit, the various implementation
of the Option pattern returning a function applying an Option on something
always used the explicit `func` signature instead of the defined type.
This change is purely with the syntax but it makes the code more readable.
> 🧼 Clean Up Option Function Signatures

- plugins/karma_test.go
- plugins/triggerer_test.go
- store/mocks/storer.go
- version.go
Move `mock` of `store` package interfaces to `gitHub.com/alexandre-normand/slackscot/store/mocks` for easier reuse. 
> 🔓 Make Mock Storer Public

- .travis.yml
- plugins/ohmonday_internal_test.go
I just heard about the pattern of using `flags` in tests to control execution such as `slow` tests. I'm usually not a fan of extra complexity like this but it's perfect of the `Oh Monday` tests that validate that all curated links are below `10 MB`. It's not so much a functional test that we need to run during fast development but it's one we want to run in continuous integration to ensure we don't add links for too-large `gif`s. 
> 🐌 Put Oh Monday Slow Tests Behind `slow` Flag and Have Travis Use It

- chatdriver.go
- plugins/ohmonday.go
- slackscot_test.go
- test/assertplugin/assertplugin_test.go
- test/capture/sendercaptor.go
- version.go
`Oh Monday` had been silent for a while. I knew this was related to a recent refactor but only got the time now to investigate. Turns out that the plugin was creating the message but never actually _sending_ it. In the process, I also found that the `RealTimeSenderCaptor` was reporting a message as _sent_ when it was actually just _created_ which was hiding this in tests. This fixes both issues.
> 😶 Fix Oh Monday Being Silent

- slackscot.go
- slackscot_test.go
- version.go
In adding support for `ephemeral` answers, there were cases where the triggering message was edited which caused a message update to be attempted. Because ephemeral messages don't have a channel id assigned and can't be updated, this caused an error to be logged. This wasn't a big issue but this change makes it more explicit that unmodifiable message ids aren't going to be tried for updates. The new behavior would be a new ephemeral message.
> 🚿 Omit Ephemeral/Non-Updatable Messages from Tracked Responses 

- config/config.go
- config/config_test.go
- go.sum
- help.go
- help_internal_test.go
- slackscot.go
- slackscot_test.go
- version.go
It can be awkward when a an old message getting updated (for example, from a job auto-archiving some content) causes a reaction. This adds the a max age threshold for message handling. Messages older than the max age (defaulting to 24 hours) are just ignored. This can be overridden by a `time.Duration` configuration via `maxAgeHandledMessages`. 
Also, this includes tests improvements to `slackscot_test.go` by using the new [UnsafeApplyMsgOptions](https://godoc.org/github.com/nlopes/slack#UnsafeApplyMsgOptions) to apply message options and assert that the content and options are as expected. 
> 🤫 Ignore Updated Messages Older than 24 Hours

- plugins/karma.go
- plugins/karma_test.go
Fixing gofmt simplification warnings from the `goreport` card.
> 🕸 Fix gofmt Simplification Warnings in karma and karma_test

- go.mod
- go.sum
- plugins/karma.go
- plugins/karma_test.go
- version.go
@jeffkole This fixes potentially awkward false positive karma recording for content enclosed a code block or inline code element. To do this, I integrated with `blackfriday` to parse the text as markdown (slack formatting can be considered a very limited subset of markdown) and only try matches against text nodes. 
I could see that also being useful in other plugins like `fingerquoter` so I might decide to integrate some markdown parsing in the `core` and add on to the `IncomingMessage`'s normalized text by passing in an additional parsed text elements. I'm not sure yet if just feeding plugins the text elements would be the right thing or not (could a plugin actually be _more_ interested in code blocks?) so I'm going to hold off doing something like that for now. 
*   [x] I've reviewed my …
> 🔖 Fix Karma Registering Content Enclosed in Code Block or Code Element

- .travis.yml
- go.mod
- go.sum
- version.go
Upgrade `nlopes/slack` to the latest in order to get the fix for https://github.com/nlopes/slack/issues/630. 
> Upgrade nlopes/slack to Fix Message Parsing

- slackscot.go
- slackscot_test.go
- version.go
@Dasio This adds retrieval of the `bot`'s user profile to include filtering on the `BotID`. This should make the self detection more robust. It would be great if you could try with this version and confirm that you don't get the original problem you reported in https://github.com/alexandre-normand/slackscot/issues/138. 🙇 
> Fetch bot id from user profile

- README.md
- config/config.go
- doc.go
- fileuploader.go
- routing.go
- routing_test.go
- slackscot.go
- slackscot_test.go
This intends to address the use-case described by @pmcintyresfdc in issue #145. 
This is still a big rough and I'll be pushing updates in the coming days but wanted to get something out to show you, @pmcintyresfdc. 
TODO: 
That said, I have that good robust test that makes me feel confident with this implementation. 
And thanks to @coderunner for having inspired the partition hashing scheme from previous work done together. I think this nice feature doesn't look too bad as far as maintenance cost goes. 
> Enable async processing of messages

- config/config.go
- config/config_test.go
- slackscot.go
- version.go
This applies all slackscot configuration defaults to any user provided configuration regardless of whether the user considered creating an instance from `config.NewViperWithDefaults` or not. 
> 🐍 Apply Slackscot Defaults to any user-provided Viper Instance

- go.mod
- go.sum
- plugins/karma.go
- plugins/karma_test.go
- version.go
The `karma` plugin came from an old hubot-based plugin back when everything was pretty much just text with proper formalization of user ids. Also, based on the modern usages of `karma`, the desire seems to be mostly to give friends and colleagues karma and not so much to record score attributed to things or ideas. Lastly, the parsing to ignore potential false positives can be tricky and never perfect..which can add more noise than can be considered acceptable. 
For all those reasons, here's a change to simplify the `karma` plugin and only record user karma recording. As a nice benefit, this also cleans up `blackfriday` as a dependency which felt a bit heavyweight for parsing to ignore false positives in code blocks.. 
*   [x] I've executed `go build …
> 🧘‍♂️ Simplify Karma Plugin and Only Support User Karma Recording

- store/datastoredb/datastoredb.go
- store/datastoredb/datastorermetrics.go
- version.go
Adding OpenTelemetry wrapper on datastoredb for more visibility on persistence calls. 
> 🔭 Add Instrumentation To datastoredb
