alexandre-normand/slackscot

- .github/ISSUE_TEMPLATE/feature_request.md
- CODE_OF_CONDUCT.md
- PULL_REQUEST_TEMPLATE.md
- README.md
Fixed most `markdown` issues flagged by `remark-lint`
> Fix Markdown Formatting Issues Identified by Remark

- slackscot.go
- slackscot_test.go
Add the skeleton for a test of the main `slackscot` core. Currently doesn't test any functionality but it's putting the pieces in place to enable testing.
> Add Draft Test for the main slackscot Core Logic

- .codeclimate.yml
- plugins/karma.go
- plugins/karma_test.go
- slackscot.go
- slackscot_test.go
* Clean up some duplication in the `karma` plugin
* Fix critical bug causing `panic` when using `ScheduledActions`
* Added tests and coverage for the `scheduler` / `scheduled actions`
> Add more tests and clean up

- store/store_test.go
Add some more tests in the `store` package surrounding the usage of `Close`
> Add Tests of store package with Close Functionality

- plugins/ohmonday.go
Add more `gifs` to `Oh Monday` and standardize on giphy's `social` version (removed `downsized` gifs).
> Add More Monday Gifs to Oh Monday

- README.md
- slackscot.go
Update `README` for the `2.0.0` release. 
> Update Documentation for 2.0.0 Release

- README.md
Add latest version and license badges to `README` since that can be useful sometimes.
> Add More Info Badges: version and license

- answer.go
- plugins/triggerer.go
- test/assertanswer/assertanswer.go
- test/assertplugin/assertplugin.go
Just a bunch of `golint` issues I missed in my last PR.
> Fix More Recent Golint Issues

- plugins/fingerquoter_test.go
`fingerquoter_test` was already partially using `assertplugin` but this completes the migration.
> Migrate FingerQuoter Test to Use assertplugin

- answer.go
- go.mod
- go.sum
- slackscot.go
- version.go
Add the ability to include `ContentBlocks` (`slack.Block`) to `Answers`. 
> Add Support for Block Kit Content in Answers

- plugins/karma.go
- plugins/karma_test.go
- slackscot.go
- version.go
This changes the top/worst reporting by using block kit formatting. It's not very pretty because there's no way to properly align things and the icons are getting cropped but it's better than before and a good starting points to make it prettier. 
> Add Block Kit Formatting for Karma Top/Worst Reporting

- slackscot_test.go
I was missing two tests in `slackscot_test` for new answers with block kit content blocks and updated answers with block kit content blocks. Both are now covered 🥇 .
> 🧹 Add Missing Tests in slackscot_test For Answers with Block Kit Content

- builder.go
- version.go
Fix a missing plugin registration in the `slackscotBuilder`. 
> 😱 Fix WithPlugin Not Doing Plugin Registration

- README.md
Update example of how to create a bot using the new fluent API.
> 🤖 Update README Example

- builder.go
- plugins/karma.go
- plugins/karma_test.go
- schedule/schedule.go
- store/datastoredb/datastoredb_internal_test.go
- store/inmemorydb/inmemorydb_test.go
- store/leveldb_test.go
- store/store.go
Fix recently introduced `gofmt` and `golint` issues.
> 🧚‍♀️Fix Recently Introduced Formatting and Linting Issues

- slackscot.go
Removes a comma and adds period and new sentence to the "I don't understand" message.
*   [ x] I've reviewed my own code
*   [ ] I've executed `go build ./...` and confirmed the build passes
*   [ ] I've run `go test ./...` and confirmed the tests pass
> Makes "I don't understand" message two sentences.

- README.md
Update configuration example in README to fix `replyBehavior.broadcast` to `replyBehavior.broadcastThreadedReplies`, and add two other items that are found inside the config package.
In particular, I spent some time scratching my head about the `broadcast` behaviour while trying to assemble [a bot](https://github.com/cflee/prime-sentinel) using Slackscot, so I thought these small updates to the README might help the next person who comes along.
*   [ ] I've reviewed my own code
*   [ ] I've executed `go build ./...` and confirmed the build passes
*   [ ] I've run `go test ./...` and confirmed the tests pass
(N/A, purely a documentation update)
> Update configuration example in README

- slackscot_test.go
Fixing minor `goling` issue introduced recently.
> 🧽 Fix Golint Issue

- .github/ISSUE_TEMPLATE/question.md
Added a new .github template for issues to address questions being asked. 
> Added a question template for github issues

- store/datastoredb/datastoredb.go
- version.go
Add `meter` to datastoredb.NewWithTelemetry`
> 🔭 Add Meter Argument to datastoredb.NewWithTelemetry

- chatdrivermetrics.go
- coremetrics.go
- emojireactormetrics.go
- fileuploadermetrics.go
- go.mod
- go.sum
- opentelemetry.template
- routing_test.go
- slackscot.go
- store/datastoredb/datastorermetrics.go
- userinfofindermetrics.go
- version.go
Upgrade to the latest open-telemetry API which is starting to look more stable. 
> 🥳 Upgrade to open-telemetry 0.6.0

- config/config_test.go
- coremetrics.go
- routing_test.go
- slackscot.go
Fixing some golint errors that sneaked in.
> 💅 Fix Some golint Errors

- plugins/karma.go
- plugins/karma_test.go
> Add support for granting/revoking karma to multiple users
